// pnpm sync - after `pnpm deploy:contract`: reads the forge broadcast, the compiled ABI and .env, checks
// the chain, and writes the two generated files the agents and the dashboard import:
//   agents/src/contract.ts   and   web/src/lib/generated/contract.ts   (plus agents/src/abi.ts)
// Overrides: UNDERCLOUD_ADDRESS + DEPLOY_BLOCK in env skip the broadcast file; SYNC_LOCAL=1 reads
// contracts/broadcast/local-run-latest.json (an anvil deployment); SYNC_SKIP_WEB=1 leaves web/ alone.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { getAddress, keccak256, stringToBytes, type Address, type Hex } from 'viem'
import pc from 'picocolors'
import { env } from '../src/env.js'
import { publicClient, RPC_URL, explorerAddr, IS_LOCAL } from '../src/chain.js'
import { REPO_DIR, AGENTS_DIR } from '../src/data.js'
import { ROLES, ROLE_LABEL, addressFor, keyFor, scoutAddressFor } from '../src/wallets.js'

const CHAIN_ID = 421614
const artifactPath = resolve(REPO_DIR, 'contracts/out/Undercloud.sol/Undercloud.json')
if (!existsSync(artifactPath)) throw new Error(`${artifactPath} missing - run \`forge build\` in contracts/ first`)
const artifact = JSON.parse(readFileSync(artifactPath, 'utf8')) as { abi: unknown[] }

// ---- 1. ABI → agents/src/abi.ts ----
const abiTs = `// GENERATED by \`pnpm sync\` from contracts/out/Undercloud.sol/Undercloud.json - do not edit.\nexport const undercloudAbi = ${JSON.stringify(artifact.abi, null, 2)} as const\n`
writeFileSync(resolve(AGENTS_DIR, 'src/abi.ts'), abiTs)
console.log(`wrote agents/src/abi.ts (${artifact.abi.length} ABI items)`)

// ---- 2. Address + deploy block ----
let address: Address, deployBlock: bigint, source: string
if (env.UNDERCLOUD_ADDRESS && env.DEPLOY_BLOCK) {
  address = getAddress(env.UNDERCLOUD_ADDRESS); deployBlock = BigInt(env.DEPLOY_BLOCK); source = 'env override'
} else {
  const file = env.SYNC_LOCAL
    ? resolve(REPO_DIR, 'contracts/broadcast/local-run-latest.json')
    : resolve(REPO_DIR, `contracts/broadcast/Deploy.s.sol/${CHAIN_ID}/run-latest.json`)
  if (!existsSync(file)) throw new Error(`${file} not found - run \`pnpm deploy:contract\` first (or set UNDERCLOUD_ADDRESS + DEPLOY_BLOCK)`)
  type Broadcast = { transactions: { transactionType: string; contractName: string | null; contractAddress: string | null; hash: string }[]; receipts?: { transactionHash: string; blockNumber: string }[] }
  const run = JSON.parse(readFileSync(file, 'utf8')) as Broadcast
  const create = run.transactions.find((t) => t.transactionType === 'CREATE' && t.contractName === 'Undercloud')
  if (!create?.contractAddress) throw new Error(`no CREATE Undercloud transaction in ${file}`)
  address = getAddress(create.contractAddress) // checksummed, so explorer links and the dashboard look right
  let block: bigint | undefined
  try {
    block = (await publicClient.getTransactionReceipt({ hash: create.hash as Hex })).blockNumber
  } catch {
    const r = run.receipts?.find((x) => x.transactionHash === create.hash)
    if (r) block = BigInt(r.blockNumber)
  }
  if (block === undefined) throw new Error(`could not find the receipt for ${create.hash} via ${RPC_URL} or in ${file}`)
  deployBlock = block; source = file.replace(REPO_DIR + '/', '')
}
console.log(`contract ${address} deployed at block ${deployBlock} (${source})`)

// ---- 3. Check the chain agrees with the repo ----
const abi = artifact.abi as any
const rubricHash = (await publicClient.readContract({ address, abi, functionName: 'rubricHash' })) as Hex
const arbiterModelId = (await publicClient.readContract({ address, abi, functionName: 'arbiterModelId' })) as string
const arbiter = (await publicClient.readContract({ address, abi, functionName: 'arbiter' })) as Address
const localRubric = keccak256(stringToBytes(readFileSync(resolve(REPO_DIR, 'contracts/rubric.md'), 'utf8')))
if (localRubric !== rubricHash) console.log(pc.red(`WARNING: contracts/rubric.md hashes to ${localRubric} but the contract committed ${rubricHash}. The arbiter will refuse to start. Did rubric.md change after deploy?`))
else console.log(`rubricHash ${rubricHash} matches contracts/rubric.md; arbiterModelId "${arbiterModelId}"; arbiter ${arbiter}`)

// ---- 4. Known agents from .env (+ the first ten per-run Scout identities) ----
const known: Record<string, { name: string; role: string }> = {}
const roleName: Record<string, string> = { DEPLOYER: 'deployer', SELLER: 'seller (treasury)', BUYER_LAB: 'buyer: AI lab procurement', BUYER_BROKER: 'buyer: GPU broker sourcing', ARBITER: 'arbiter (Judge)' }
let haveKeys = true
try { for (const r of ROLES) keyFor(r) } catch { haveKeys = false }
if (haveKeys) {
  for (const r of ROLES) known[addressFor(r)] = { name: ROLE_LABEL[r], role: roleName[r] }
  for (let i = 0; i < 10; i++) known[scoutAddressFor(keyFor('SELLER'), i)] = { name: `Scout (run ${i + 1})`, role: 'seller' }
  if (arbiter !== addressFor('ARBITER')) console.log(pc.yellow(`note: ARBITER_PRIVATE_KEY in .env derives ${addressFor('ARBITER')} but the contract's arbiter is ${arbiter}`))
} else console.log(pc.yellow('no agent keys in .env - knownAgents left empty (run `pnpm keygen` then `pnpm sync` again)'))

// ---- 5. Write the generated files ----
const knownTs = `{\n${Object.entries(known).map(([a, v]) => `  '${a}': { name: ${JSON.stringify(v.name)}, role: ${JSON.stringify(v.role)} },`).join('\n')}\n}`
const agentsTs = `// GENERATED by \`pnpm sync\` (${new Date().toISOString()}) - do not edit. Source: ${source}.
// UNDERCLOUD_ADDRESS / DEPLOY_BLOCK in .env override these (used for local anvil runs).
import type { Address, Hex } from 'viem'
import { env } from './env.js'
export { undercloudAbi as abi } from './abi.js'

export const chainId = ${CHAIN_ID}
export const address = (env.UNDERCLOUD_ADDRESS || '${address}') as Address
export const deployBlock = BigInt(env.DEPLOY_BLOCK || '${deployBlock}')
export const rubricHash = '${rubricHash}' as Hex
export const arbiterModelId = ${JSON.stringify(arbiterModelId)}
export const knownAgents: Record<Address, { name: string; role: string }> = ${knownTs}
`
writeFileSync(resolve(AGENTS_DIR, 'src/contract.ts'), agentsTs)
console.log('wrote agents/src/contract.ts')

if (env.SYNC_SKIP_WEB) console.log('SYNC_SKIP_WEB set - web/src/lib/generated/contract.ts untouched')
else {
  const webDir = resolve(REPO_DIR, 'web/src/lib/generated')
  mkdirSync(webDir, { recursive: true })
  const webTs = `// GENERATED by \`pnpm sync\` (agents/scripts/sync.ts, ${new Date().toISOString()}) - do not edit by hand.
// Committed on purpose: the dashboard needs no env vars. NEXT_PUBLIC_UNDERCLOUD_ADDRESS / NEXT_PUBLIC_DEPLOY_BLOCK
// still override at build time (same convention as the pre-deploy placeholder).
export const chainId = ${CHAIN_ID}
export const address = ((process.env.NEXT_PUBLIC_UNDERCLOUD_ADDRESS as \`0x\${string}\` | undefined) ?? '${address}') as \`0x\${string}\`
export const deployBlock = BigInt(process.env.NEXT_PUBLIC_DEPLOY_BLOCK ?? '${deployBlock}')
export const rubricHash = '${rubricHash}' as \`0x\${string}\`
export const arbiterModelId = ${JSON.stringify(arbiterModelId)}
export const arbiter = '${arbiter}' as \`0x\${string}\`
/** GitHub URL of this repo (REPO_URL in .env at sync time) - the header's source links; '' falls back to NEXT_PUBLIC_REPO_URL. */
export const repoUrl = ${JSON.stringify((env.REPO_URL ?? '').replace(/\/+$/, ''))}
/** Agent wallets, for display names in the dashboard (per-run Scout identities are pre-labelled). */
export const knownAgents: Record<string, { name: string; role: string }> = ${knownTs}
export const undercloudAbi = ${JSON.stringify(artifact.abi, null, 2)} as const
export const abi = undercloudAbi
`
  writeFileSync(resolve(webDir, 'contract.ts'), webTs)
  console.log(`wrote web/src/lib/generated/contract.ts${env.REPO_URL ? ` (source links -> ${env.REPO_URL})` : pc.yellow(' (REPO_URL not set in .env: the dashboard\'s "Undercloud.sol" / "rubric" links will use NEXT_PUBLIC_REPO_URL or a placeholder - set REPO_URL after the GitHub push and run pnpm sync again)')}`)
}

// ---- 6. What to do next ----
console.log(`
Contract: ${IS_LOCAL ? `${address} (local anvil)` : explorerAddr(address)}
If Arbiscan does not show "Contract Source Code Verified" yet, run:
  pnpm verify:contract
(or by hand, from contracts/:  forge verify-contract --chain 421614 --etherscan-api-key "$ETHERSCAN_API_KEY" --watch \\
   --constructor-args "$(cast abi-encode 'constructor(address,bytes,string,bytes32,uint64,uint64,uint64)' "$ARBITER_ADDRESS" "$ARBITER_PUBKEY" claude-opus-5 ${rubricHash} 90 180 600)" \\
   ${address} src/Undercloud.sol:Undercloud)
Next: pnpm fund  →  pnpm demo
`)
