// GENERATED by `pnpm sync` (2026-09-11T09:11:40.939Z) - do not edit. Source: contracts/broadcast/Deploy.s.sol/421614/run-latest.json.
// UNDERCLOUD_ADDRESS / DEPLOY_BLOCK in .env override these (used for local anvil runs).
import type { Address, Hex } from 'viem'
import { env } from './env.js'
export { undercloudAbi as abi } from './abi.js'

export const chainId = 421614
export const address = (env.UNDERCLOUD_ADDRESS || '0xb24cA3C97Cc483aF9c1bB24b9D89F2C7461312eb') as Address
export const deployBlock = BigInt(env.DEPLOY_BLOCK || '307715235')
export const rubricHash = '0x4189c5bc778e46d42d6ee85f1a4e17cf78147ff4be4ad7de2ada16473b70fdd1' as Hex
export const arbiterModelId = "claude-opus-5"
export const knownAgents: Record<Address, { name: string; role: string }> = {
  '0xa486cEdAA877e3CCE052978C6A87e7E4E0625F76': { name: "Deployer", role: "deployer" },
  '0xb5a1F4Ca83899Fd4678F49EAC9468641d49f3445': { name: "Scout treasury", role: "seller (treasury)" },
  '0xa6d9bF637CA2041895c7346A972976C4BCc28b62': { name: "Brineholt Labs agent", role: "buyer: AI lab procurement" },
  '0x188596Bd39619088ee9D73fC72F47697747d164B': { name: "Sounding Compute agent", role: "buyer: GPU broker sourcing" },
  '0x85FD1e11b0259cE3Cc8ae28c986f7E99D5f1cd2f': { name: "Judge", role: "arbiter (Judge)" },
  '0xAD223127C42e9517359128a700740A077d543380': { name: "Scout (run 1)", role: "seller" },
  '0x120fAc606FF46141EC78041c70819c80347276fd': { name: "Scout (run 2)", role: "seller" },
  '0x51c1dc6d5383DE12Af44b1F41D94f35A7aAA88A2': { name: "Scout (run 3)", role: "seller" },
  '0x50B83F879919E1F8c2A30Bb03a2BdF079e4d45b6': { name: "Scout (run 4)", role: "seller" },
  '0xC6DB9b8565F96691498554b349c64927a1A302E5': { name: "Scout (run 5)", role: "seller" },
  '0x1fe907b9992ef47335A0Cb1235b8bb6273e756Ab': { name: "Scout (run 6)", role: "seller" },
  '0x4e186f02cb35A1D5BBEbEb16993E90c02C9BA4Ef': { name: "Scout (run 7)", role: "seller" },
  '0x2Cc14E4500dc4a8A40b016BCb108eA97D466EE4c': { name: "Scout (run 8)", role: "seller" },
  '0x3379890104A30Ae48dfd5109f68d68E713c38E2a': { name: "Scout (run 9)", role: "seller" },
  '0x87feFda99cb28D0D9DDA1a6439a2F6513AbDC1Bd': { name: "Scout (run 10)", role: "seller" },
}
